INSERT INTO users VALUES (1, 'James', 'Carter') ON CONFLICT DO NOTHING;
INSERT INTO users VALUES (2, 'Helen', 'Leary') ON CONFLICT DO NOTHING;
INSERT INTO users VALUES (3, 'Linda', 'Douglas') ON CONFLICT DO NOTHING;
INSERT INTO users VALUES (4, 'Rafael', 'Ortega') ON CONFLICT DO NOTHING;
INSERT INTO users VALUES (5, 'Henry', 'Stevens') ON CONFLICT DO NOTHING;
INSERT INTO users VALUES (6, 'Sharon', 'Jenkins') ON CONFLICT DO NOTHING;
